-- Esquema inicial de MiCarro.
--
-- Representa el esquema que Hibernate generaba automáticamente con
-- ddl-auto=update. A partir de ahora Flyway es la única fuente de verdad
-- y Hibernate solo valida (ddl-auto=validate).

create table products (
    id bigint generated by default as identity,
    name varchar(255),
    brand varchar(255),
    category varchar(255),
    external_id varchar(255),
    image_url varchar(255),
    format varchar(255),
    price numeric(38, 2),
    primary key (id),
    constraint uk_products_external_id unique (external_id)
);

create table users (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (id),
    constraint uk_users_email unique (email)
);

create table user_favorites (
    id bigint generated by default as identity,
    user_id bigint not null,
    product_id bigint not null,
    primary key (id),
    constraint uk_user_favorite_product unique (user_id, product_id),
    constraint fk_user_favorites_user
        foreign key (user_id) references users,
    constraint fk_user_favorites_product
        foreign key (product_id) references products
);

create table shopping_plan_history (
    id bigint generated by default as identity,
    user_id bigint not null,
    budget numeric(38, 2) not null,
    estimated_total numeric(38, 2) not null,
    mode varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint ck_shopping_plan_history_mode
        check (mode in ('CHEAP', 'BALANCED', 'QUALITY')),
    constraint fk_shopping_plan_history_user
        foreign key (user_id) references users
);

create table shopping_plan_history_item (
    id bigint generated by default as identity,
    history_id bigint not null,
    product_id bigint,
    product_name varchar(255),
    brand varchar(255),
    format varchar(255),
    image_url varchar(255),
    quantity integer,
    unit_price numeric(38, 2),
    subtotal numeric(38, 2),
    primary key (id),
    constraint fk_shopping_plan_history_item_history
        foreign key (history_id) references shopping_plan_history
);
