-- Planes guardados por el usuario (desde el carrito).
--
-- El snapshot de cada item se crea en el backend a partir del catálogo en el
-- momento de guardar (productName, brand, format, imageUrl, unitPrice, subtotal).
-- product_id no es FK: el plan debe sobrevivir a bajas del catálogo.

create table saved_plans (
    id bigint generated by default as identity,
    user_id bigint not null,
    name varchar(80) not null,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_saved_plans_user
        foreign key (user_id) references users
);

create table saved_plan_items (
    id bigint generated by default as identity,
    plan_id bigint not null,
    product_id bigint,
    product_name varchar(255),
    brand varchar(255),
    format varchar(255),
    image_url varchar(255),
    quantity integer not null,
    unit_price numeric(38, 2),
    subtotal numeric(38, 2),
    primary key (id),
    constraint fk_saved_plan_items_plan
        foreign key (plan_id) references saved_plans
);