-- Historial real de precios (change-log por producto).
--
-- Se inserta una fila al crear el producto y otra SOLO cuando su precio cambia
-- en la sincronización. Cada fila representa el precio vigente desde su
-- recorded_at hasta la siguiente fila (o hasta ahora).

create table product_price_history (
    id bigint generated by default as identity,
    product_id bigint not null,
    price numeric(38, 2) not null,
    recorded_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_product_price_history_product
        foreign key (product_id) references products
);

create index ix_product_price_history_product_recorded
    on product_price_history (product_id, recorded_at);

-- Backfill de los productos existentes: se ancla el PRECIO ACTUAL a now().
-- No inventamos precios pasados: no sabemos qué precio tenían antes, así que
-- el histórico real empieza en la activación de esta funcionalidad. Esto evita
-- falsas bajadas/subidas hasta que ocurra un cambio real de precio.
insert into product_price_history (product_id, price, recorded_at)
select id, price, now()
from products
where price is not null;